language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

# Install test dependencies. TravisCI gives us nose, mock, and pytest by default
install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - "coverage run --source=uiautomator setup.py nosetests"
  - "python setup.py sdist"

after_success:
  coveralls
